<?php

/**
 * Test stub for OpenRegister's ObjectEntity.
 *
 * Minimal surface needed by dossiq unit tests: the audit listener resolves an
 * ObjectEntity from OR's ObjectService and hands it to AuditTrailMapper. Only
 * the accessors the dossiq code touches are stubbed.
 *
 * @category Stub
 * @package  OCA\OpenRegister\Db
 *
 * @author    Conduction Development Team <info@conduction.nl>
 * @copyright 2026 Conduction B.V.
 * @license   EUPL-1.2 https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12
 *
 * SPDX-License-Identifier: EUPL-1.2
 * SPDX-FileCopyrightText: 2026 Conduction B.V. <info@conduction.nl>
 *
 * @link https://conduction.nl
 */

declare(strict_types=1);

namespace OCA\OpenRegister\Db;

/**
 * Stub of OpenRegister's ObjectEntity for unit tests.
 */
class ObjectEntity implements \OCA\OpenRegister\Contract\ObjectEntityInterface {
	/**
	 * @return ?string
	 */
	public function getRegister(): ?string {
		return $this->register ?? null;
	}

	/**
	 * @return ?string
	 */
	public function getSchema(): ?string {
		return $this->schema ?? null;
	}

	/**
	 * @return ?string
	 */
	public function getOrganisation(): ?string {
		return $this->organisation ?? null;
	}

	/**
	 * @return ?string
	 */
	public function getOwner(): ?string {
		return $this->owner ?? null;
	}

	/**
	 * Object UUID.
	 *
	 * @var string|null
	 */
	private ?string $uuid = null;

	/**
	 * Raw object data (excl. `@self`).
	 *
	 * @var array<string, mixed>
	 */
	private array $object = [];

	/**
	 * Schema identifier surfaced under `@self.schema` by jsonSerialize().
	 *
	 * Named `schema`, as the real entity's column is. The name is load-bearing
	 * on the real class, where the accessors are generated by
	 * `OCP\AppFramework\Db\Entity::__call` over the DECLARED properties, so a
	 * property the real class does not declare is a setter that does not exist.
	 *
	 * @var string|null
	 */
	private ?string $schema = null;

	/**
	 * Get the object UUID.
	 *
	 * @return string|null
	 */
	public function getUuid(): ?string {
		return $this->uuid;
	}//end getUuid()

	/**
	 * Set the object UUID.
	 *
	 * @param string|null $uuid The UUID
	 *
	 * @return void
	 */
	public function setUuid(?string $uuid): void {
		$this->uuid = $uuid;
	}//end setUuid()

	/**
	 * Set the raw object data.
	 *
	 * @param array<string, mixed> $object Object data
	 *
	 * @return void
	 */
	public function setObject(array $object): void {
		$this->object = $object;
	}//end setObject()

	/**
	 * Get the raw object data (excl. `@self`).
	 *
	 * @return array<string, mixed>
	 */
	public function getObject(): array {
		return $this->object;
	}//end getObject()

	/**
	 * Set the schema identifier surfaced under `@self.schema`.
	 *
	 * 🔴 `setSchemaId()` USED TO SIT BESIDE THIS, AND IS GONE.
	 *
	 * The real ObjectEntity declares no `schemaId` property, so it serves no
	 * `setSchemaId()`: the call raises
	 * `BadFunctionCallException: schemaId is not a valid attribute`. The stub
	 * offered it anyway, and 23 assertions across three listener suites were
	 * written against a method that exists nowhere but here. Nothing in `lib/`
	 * called it — checked, twice, and the drift check now keeps checking —
	 * but that was luck, not design, and it is exactly how a stub-only method
	 * reaches production code.
	 *
	 * @param string|null $schema Schema identifier.
	 *
	 * @return void
	 */
	public function setSchema(?string $schema): void {
		$this->schema = $schema;
	}//end setSchema()

	/**
	 * Minimal stand-in for the real ObjectEntity::jsonSerialize() — merges
	 * the raw object data with an `@self.schema` (and `@self.id`) envelope,
	 * matching the fields dossiq listeners actually read.
	 *
	 * @return array<string, mixed>
	 */
	public function jsonSerialize(): array {
		$data = $this->object;
		$data['@self'] = [
			'schema' => $this->schema,
			'id' => $this->uuid,
		];

		// 🔴 TOP-LEVEL id, because the real class guarantees one.
		//
		// OCA\OpenRegister\Db\ObjectEntity::jsonSerialize() sets
		// `$object['id'] = $this->uuid` under a comment reading "Ensure id is
		// always accessible at top level (not just in @self)". This stub put
		// it only in @self, so VergunningaanvraagCreatedListener — which reads
		// `$object['id']`, correctly — found none and returned early.
		//
		// The test that would have caught it was SKIPPING, because
		// ObjectCreatedEvent had no stub and `class_exists()` said so. A skip
		// cannot tell "not applicable" from "broken".
		if ($this->uuid !== null && isset($data['id']) === false) {
			$data['id'] = $this->uuid;
		}

		return $data;
	}//end jsonSerialize()
}//end class
