name: Code Quality

on:
  push:
    branches: [main, development, feature/**, bugfix/**, hotfix/**]
  pull_request:
    branches: [main, master, development]
  workflow_dispatch:

jobs:
  quality:
    uses: ConductionNL/.github/.github/workflows/quality.yml@main
    with:
      app-name: procest
      php-version: "8.3"
      php-test-versions: '["8.3", "8.4"]'
      nextcloud-test-refs: '["stable31", "stable32"]'
      enable-psalm: true
      enable-phpstan: true
      enable-phpmetrics: false
      enable-frontend: true
      enable-eslint: true
      enable-phpunit: true
      enable-newman: true
      newman-collection-path: "data"
      newman-environment-path: "tests/zgw/zgw-environment.json"
