name: Code Quality

on:
  push:
    branches: [main, development, feature/**, bugfix/**, hotfix/**]
  pull_request:
    branches: [main, master, development]

permissions:
  pull-requests: write

jobs:
  quality:
    uses: ConductionNL/.github/.github/workflows/quality.yml@main
    with:
      app-name: procest
      php-version: "8.3"
      enable-psalm: true
      enable-phpstan: true
      enable-phpmetrics: false
      enable-frontend: true
      enable-eslint: true
